[package]
name = "rust_star"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc-hash = "2.1.1"
rand = "*"
log = "0.4.27"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[profile.release]
debug = true